Script adjustments
buanet/ioBroker.docker pull request #353
Opened 2023-07-07 07:29 UTC by dontobi

I looked at all the scripts and swapped the ' for " in some echos to make it consistent.

I also added the parameter "--no-install-recommends" when installing new packages.

2023-07-07 20:25 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +    #echo "$packages" > /opt/scripts/.docker_config/.packages
Die Zeile kann raus.

2023-07-07 20:26 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +  echo -n "Registering maintenance script as command..."
Leerzeichen erwünscht.

2023-07-07 20:27 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +  echo -n "Restoring initial ioBroker installation..."
Leerzeichen erwünscht.

2023-07-07 20:27 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +echo "Done."
Einrückung erwünscht.

2023-07-07 20:28 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +echo -n "Fixing \"sudo-bug\" by replacing sudo with gosu..."
Leerzeichen erwünscht.

2023-07-07 20:28 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +    echo -n "Updating hostname to \"""$(hostname)""\"..."
Leerzeichen erwünscht.

2023-07-07 20:28 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +    echo "Setting Adminport to \"""$adminport""\"..."
Leerzeichen erwünscht.

2023-07-07 20:29 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +  echo "AVAHI is \"true\". Running setup script..."
Leerzeichen erwünscht.

2023-07-07 20:29 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +  echo "ZWAVE is \"true\". Running setup script..."
Leerzeichen erwünscht.

2023-07-07 20:29 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +    echo "Running userscript_firststart.sh..."
Leerzeichen erwünscht.

2023-07-07 20:29 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +    echo "Userscript for every start detected. Running userscript_everystart.sh..."
Leerzeichen erwünscht.

2023-07-07 20:30 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +echo "Starting ioBroker..."
Leerzeichen erwünscht.

2023-07-07 20:30 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +  echo "Shutting down ioBroker..."
Leerzeichen erwünscht.

2023-07-07 20:30 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +      echo -e '\nTimeout reached. Killing remaining processes...'
Leerzeichen erwünscht.

2023-07-07 20:32 UTC, buanet commented on debian/scripts/maintenance.sh
> +    echo "Activating maintenance mode..."
hier könnte ein -n rein und am Ende ein Leerzeichen hinter den Punkten.

2023-07-07 20:34 UTC, buanet commented on debian/scripts/maintenance.sh
> +  echo -e "\nDone."
mhh, weiß nicht ob das klappt...

2023-07-07 20:36 UTC, buanet commented on debian/scripts/setup_avahi.sh
> +echo -n "[setup_avahi.sh] Starting avahi-daemon..."
Leerzeichen erwünscht.

2023-07-07 20:44 UTC, buanet requested changes
Kann man sich jetzt drüber streiten ob es sinn macht die echos mit " statt ' zu machen, aber von mir aus soll es so sein :) Allerdings hätte ich gerne die Leerzeichen hinter `...` wieder. Eigentlich sollte immer ein Leerzeichen drin sein, falls das `Done.` im Log in die gleiche Zeile kommt. Sieht einfach sauberer aus.

2023-07-08 04:52 UTC, dontobi commented
Ich kann mit dem Leerzeichen leben. Die andere Angelegenheit beruht auf meinen Einstellungen in VSCode. Sieht dann sauberer aus.

2023-07-08 06:16 UTC, dontobi commented
Ich habe die Anpassungen mal schnell eingepflegt. Ein Review wäre nun gut.

2023-07-08 20:17 UTC, buanet requested changes
Ein Leerzeichen habe ich noch gefunden. :) Und ich habe als Target mal die Beta Branch genommen. Dann nehme ich das gleich mit in die kommende (letzte) v8.1.0-beta.4.

MfG,
André

2023-07-08 20:17 UTC, buanet commented on debian/scripts/iobroker_startup.sh
> +  echo -n "Changing UID to \"""$setuid""\" and GID to \"""$setgid""\"..."
Hier ist noch ein verlorenes Leerzeichen. :)

2023-07-09 19:58 UTC, buanet commented
Mhh, ich kriegs gerade nicht auf die Reihe.
Du hast doch heute morgen beta in deine branch gemerged: 
![image](https://github.com/buanet/ioBroker.docker/assets/16137672/fb5e1d5d-5cb3-4d8d-b157-2a3ba5159270)
Warum will github mir denn jetzt mit deinem PR die letzten Änderungen des maintenance scripts in beta von gestern wieder raus schmeißen? 
Scheinen auch irgendwie in deiner branch nicht angekommen zu sein: https://github.com/buanet/ioBroker.docker/commit/700d7609ccf5860bb823d8706324a9567e6fe4a6
Kannst du da mal schauen?

2023-07-10 05:12 UTC, dontobi commented
Ich finde den Fehler aktuell nicht. Ich mache einen manuellen Sync meines Branch und mache dann einen neuen PR auf.

2023-07-10 05:12 UTC, closed without merging